export const GET_WORDS = "GET_WORDS";
export const GET_WORDS_LOADING = "GET_WORDS_LOADING";
export const GET_WORDS_LOADING_END = "GET_WORDS_LOADING_END";
export const GET_WORDS_LOADING_ERROR = "GET_WORDS_LOADING_ERROR";